# ===========================================
# Docker Compose para Maestría en Datos
# Universidad Anáhuac - Bases de Datos e Inteligencia de Negocios
# Actualizado para Docker Compose V2.27.0+
# ===========================================

name: maestria-anahuac-datos

services:
  mysql:
    image: mysql:8.0
    container_name: maestria_mysql
    restart: unless-stopped
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
      --default-authentication-plugin=mysql_native_password
      --sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
      --innodb_file_per_table=1
      --max_connections=200
      --innodb_buffer_pool_size=512M
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - maestria_network

  adminer:
    image: adminer:4.8.1
    container_name: maestria_adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: pepa-linha
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - maestria_network

  metabase:
    image: metabase/metabase:v0.51.2
    container_name: maestria_metabase
    restart: unless-stopped
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      JAVA_TOOL_OPTIONS: "${METABASE_JAVA_OPTS}"
      MB_SITE_LOCALE: "${METABASE_SITE_LOCALE}"
      MB_SITE_NAME: "${METABASE_SITE_NAME}"
      MB_JETTY_PORT: 3000
      MB_EMOJI_IN_LOGS: false
      MB_COLORIZE_LOGS: true
      MB_SEND_EMAIL_ON_FIRST_LOGIN_FROM_NEW_DEVICE: false
    ports:
      - "${METABASE_PORT:-3000}:3000"
    volumes:
      # Datos organizados en carpeta específica
      - ./data/metabase:/metabase-data
      # Logs organizados
      - ./logs/metabase:/logs
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - maestria_network

  mysql_backup:
    image: fradelg/mysql-cron-backup:latest
    container_name: maestria_mysql_backup
    restart: unless-stopped
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASSWORD}
      CRON_TIME: "${BACKUP_CRON_TIME}"
      MAX_BACKUPS: "${BACKUP_MAX_BACKUPS}"
      TZ: ${TZ}
      MYSQLDUMP_OPTS: "--databases ${MYSQL_DATABASE} --routines --events --single-transaction --quick --lock-tables=false --add-drop-database"
      GZIP_LEVEL: 6
    volumes:
      # Backups organizados por fecha
      - ./backups:/backup
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - maestria_network

  superset:
    image: apache/superset:latest  # ← Corregido: versión disponible
    container_name: maestria_superset
    restart: unless-stopped
    environment:
      SUPERSET_ENV: "${SUPERSET_ENV}"
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SUPERSET_LOAD_EXAMPLES: "${SUPERSET_LOAD_EXAMPLES}"
      TZ: ${TZ}
      PYTHONPATH: /app/pythonpath:/app/superset_home
      SUPERSET_CONFIG_PATH: /app/superset_home/superset_config.py
    ports:
      - "${SUPERSET_PORT:-8088}:8088"
    volumes:
      # Configuración y datos organizados
      - ./data/superset:/app/superset_home
      - ./config/superset:/app/pythonpath
      # Logs organizados
      - ./logs/superset:/app/logs
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - maestria_network

  # Servicio adicional para análisis de datos
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: maestria_jupyter
    restart: unless-stopped
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "maestria2024"
      TZ: ${TZ}
    ports:
      - "8888:8888"
    volumes:
      # Notebooks organizados
      - ./notebooks:/home/jovyan/work
      - ./data/datasets:/home/jovyan/datasets:ro
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - maestria_network

# Volúmenes nombrados para mejor gestión
volumes:
  mysql_data:  # ← Corregido: volumen simple sin bind mount
    driver: local

# Red personalizada optimizada
networks:
  maestria_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
    driver_opts:
      com.docker.network.bridge.name: maestria_br
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"